

title:      划船全靠浪的网站
longtitle:  划船全靠浪的网站
author:     武锦旗
email:      596160575@qq.com
description: >
  一次搭建个人博客网站的尝试


remote_theme: sighingnow/jekyll-gitbook

syntax_highlighter_style: colorful

toc:
  enabled: true
  h_min: 1
  h_max: 3
